name: MCTag
version: 2.0
main: com.hawkfalcon.mctag.MCTag      
authors: [hawkfalcon, gomeow]
website: http://dev.bukkit.org/server-mods/put-slug-here/
permissions:  
    mctag.tag:
       description: Allows use of /tag
       default: true
